// This file is generated by icon spritesheet generator

export type IconName =
  | "WavesIcon"
  | "TicketIcon"
  | "StarIcon"
  | "ShirtIcon"
  | "SailboatIcon"
  | "Ruler"
  | "GaugeIcon"
  | "CompassIcon"
  | "CardStack"
  | "Camera"
  | "CalendarIcon"
  | "CalendarDaysIcon"
  | "CalendarCheckIcon"
  | "BedSvgrepoCom"
  | "AnchorIcon"

export const iconNames = [
  "WavesIcon",
  "TicketIcon",
  "StarIcon",
  "ShirtIcon",
  "SailboatIcon",
  "Ruler",
  "GaugeIcon",
  "CompassIcon",
  "CardStack",
  "Camera",
  "CalendarIcon",
  "CalendarDaysIcon",
  "CalendarCheckIcon",
  "BedSvgrepoCom",
  "AnchorIcon",
] as const
